### ISSUE TITLE
Sorry, I can't reproduce your code

### ISSUE THREAD

**Issue by 52gentleman** [Yang-Liu1082/InvDN#16]
I have some trouble. I can't solve it. I'm sorry

Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 107, in main
    train_set = create_dataset(dataset_opt)
  File "/InvDN-main/codes/data/__init__.py", line 36, in create_dataset
    dataset = D(dataset_opt)
  File "/InvDN-main/codes/data/LQGTRN_dataset.py", line 25, in __init__
    self.paths_GT, self.sizes_GT = util.get_image_paths(self.data_type, opt['dataroot_GT'])
  File "/InvDN-main/codes/data/util.py", line 52, in get_image_paths
    paths = sorted(_get_paths_from_images(dataroot))
  File "/InvDN-main/codes/data/util.py", line 23, in _get_paths_from_images
    assert os.path.isdir(path), '{:s} is not a valid directory'.format(path)
AssertionError:  is not a valid directory

Traceback (most recent call last):
  File "/InvDN-main/codes/train.py", line 250, in <module>
    main()
  File "/InvDN-main/codes/train.py", line 37, in main
    opt = option.parse(args.opt, is_train=True)
  File "\InvDN-main\codes\options\options.py", line 10, in parse
    with open(opt_path, mode='r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by mengchuangji** [comment]
The original SIDD dataset is not a folder structure like the author's /SIDD_Medium_Srgb/GT and SIDD_Medium_Srgb/Noisy, but a SIDD_Medium_Srgb\Data\0001_001_S6_00100_00060_3200_L\*GT*.png or *NOISY*.png like this. Please tell me how the author runs the code.
